language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install: "make"
script:
  - make test
notifications:
  email:
    on_success: never
    on_failure: always
